[build]
  functions = "./netlify/functions"
  publish = "./dist"
  command = "npm run build"

[dev]
  framework = "vite"
  port = 8888
  targetPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 