[build]
  functions = "./netlify/functions"
  publish = "./dist"
  command = "npm run build"

[dev]
  framework = "vite"
  port = 8890
  targetPort = 5173
  functionsPort = 8891
  functions = "./netlify/functions"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 